server.port=8092

#DATABASE CONFIG
DB_HOST=13.127.69.168
DB_PORT=3306
EMPLOYEE_DB_NAME=employee_service_db
DB_USERNAME=admin
DB_PASSWORD=Edunomic@2025

#APP PROP
ACCESS_KEY_ID=local
ACCESS_KEY_SECRETE=local

#APPLICATION URI
MASTER_BASE_URL=http://localhost:8085/master
ORG_BASE_URL=http://localhost:8090/organization