server.port=8087

#DATABASE CONFIG
DB_HOST=13.127.69.168
DB_PORT=3306
FINANCE_DB_NAME=finance_management_db
DB_USERNAME=admin
DB_PASSWORD=Edunomic@2025

#APP PROP
ACCESS_KEY_ID=local
AACCESS_KEY_SECRETE=local

#APPLICATION URI
MASTER_BASE_URL=http://localhost:8085/master
ORGANIZATION_BASE_URL=http://localhost:8090/organization
STUDENT_BASE_URL=http://localhost:8091/student
ADMISSION_BASE_URL=http://localhost:8084/admission
