server.port=8085

#DATABASE CONFIG
DB_HOST=13.127.69.168
DB_PORT=3306
MASTER_DB_NAME=master_service_db
DB_USERNAME=admin
DB_PASSWORD=Edunomic@2025

# APPLICATION CONFIG
MASTER_BASE_URL=http://localhost:8085/master
ACCESS_KEY_ID=local
ACCESS_KEY_SECRETE=local