server.port=8088

#DATABASE CONFIG
DB_HOST=13.127.69.168
DB_PORT=3306
LEAD_DB_NAME=notification_manager_db
DB_USERNAME=admin
DB_PASSWORD=Edunomic@2025

#APP PROP
ACCESS_KEY_ID=local
ACCESS_KEY_SECRETE=local

#API URL
MASTER_BASE_URL=http://localhost:8085/master
