server.port=8090

#DATABASE CONFIG
DB_HOST=13.127.69.168
DB_PORT=3306
ACADEMIC_DB_NAME=org_service_db
DB_USERNAME=admin
DB_PASSWORD=Edunomic@2025

#APPLICATION URI
STUDENT_BASE_URL=http://localhost:8091/student