services:
  - repo_url: "https://bitbucket.org/edunomic/api-gateway-service.git"
    target_dir: "codebase/api-gateway-service"
    branch_name: "develop"
    project_name: "api_gateway_service"
    jar_name: "gateway-0.0.1-SNAPSHOT.jar"
    env_file: "config/api-gateway-config.properties"
    log_dir: api_logs

  - repo_url: "https://bitbucket.org/edunomic/lead-management-service.git"
    target_dir: "codebase/lead-management-service"
    branch_name: "EW-139_lead_changes"
    project_name: "lead_management_service"
    jar_name: "lead-managment-0.0.1-SNAPSHOT.jar"
    env_file: "config/lead-management-config.properties"
    log_dir: api_logs

  - repo_url: "https://bitbucket.org/edunomic/master-service.git"
    target_dir: "codebase/master-service"
    branch_name: "develop"
    project_name: "master_service"
    jar_name: "master-service-0.0.1-SNAPSHOT.jar"
    env_file: "config/master-service-config.properties"
    log_dir: api_logs

  - repo_url: "https://bitbucket.org/edunomic/org-services.git"
    target_dir: "codebase/org-services"
    branch_name: "develop"
    project_name: "org_services"
    jar_name: "org-service-0.0.1-SNAPSHOT.jar"
    env_file: "config/org-services-config.properties"
    log_dir: api_logs

  - repo_url: "https://bitbucket.org/edunomic/student-management.git"
    target_dir: "codebase/student-management"
    branch_name: "develop"
    project_name: "student_management"
    jar_name: "student-management-0.0.1-SNAPSHOT.jar"
    env_file: "config/student-management-config.properties"
    log_dir: api_logs

  - repo_url: "https://bitbucket.org/edunomic/finance-manager.git"
    target_dir: "codebase/finance-manager"
    branch_name: "develop"
    project_name: "finance_manager"
    jar_name: "finance-manager-0.0.1-SNAPSHOT.jar"
    env_file: "config/finance-manager-config.properties"
    log_dir: api_logs