server.port=8084

#DATABASE CONFIG
DB_HOST=localhost
DB_PORT=3311
ADMISSION_DB_NAME=EDUNOMIC_ERP
DB_USERNAME=admin
DB_PASSWORD=Edunomic@123

#APP PROP
ACCESS_KEY_ID=local
ACCESS_KEY_SECRETE=local

#APPLICATION URI
ORGANIZATION_BASE_URL=http://localhost:8090/organization
STUDENT_BASE_URL=http://localhost:8091/student
MASTER_BASE_URL=http://localhost:8085/master
EMPLOYEE_BASE_URL=http://localhost:8092/employee