#SERVER PORT
server.port=8080
#############
SONAR_URL=/admin/swagger-ui
FINANCE_SWAGER_UI=/finance/swagger-ui
ACADEMIC_SWAGER_UI=/academic/swagger-ui
ADMISSION_SWAGGER_URL=/admission/swagger-ui
MASTER_SWAGGER_URL=/master/swagger-ui
EDUMIND_AI_SWAGGER_URL=/edumind-ai/swagger-ui


#API GATEWAY KEYS
# BASE_URL=http://localhost:8081
# BASE_URL_FINANCE=http://localhost:8082

ACADEMIC_BASE_URL=http://localhost:8083
ADMISSION_BASE_URL=http://localhost:8084/admission
MASTER_BASE_URL=http://localhost:8085/master
ADMIN_BASE_URL=http://localhost:8086
FINANCE_BASE_URL=http://localhost:8087/finance
NOTIFICATION_BASE_URL=http://localhost:8088/notification
EXAM_BASE_URL=http://localhost:8089
ORGANIZATION_BASE_URL=http://localhost:8090/organization
STUDENT_BASE_URL=http://localhost:8091/student
EMPLOYEE_BASE_URL=http://localhost:8092/employee
LEAD_BASE_URL=http://localhost:8093/lead
EDUMIND_AI_BASE_URL=http://localhost:8094

CLIENT_ID=CLIENT_ID
GMAIL-CLIENT-ID=421543565413-fpeuac08lf4e6j52sb2ltf1htfeqs71v.apps.googleusercontent.com
GMAIL-CLIENT-SCOPE=profile email openid
GMAIL-TOKEN-TYPE=token
#JWT TOKEN SECRET
jwt.secret=K9fL2x!Qz7vB@eR4hT8wYpM1nC3sD6uJ0aZ5gXqV2rF9oLkE