server.port=8092

#DATABASE CONFIG
DB_HOST=localhost
DB_PORT=3310
EMPLOYEE_DB_NAME=EDUNOMIC_ERP
DB_USERNAME=admin
DB_PASSWORD=Edunomic@123

#APP PROP
ACCESS_KEY_ID=local
ACCESS_KEY_SECRETE=local

#APPLICATION URI
MASTER_BASE_URL=http://localhost:8085/master
ORG_BASE_URL=http://localhost:8090/organization