server.port=8087

#DATABASE CONFIG
DB_HOST=localhost
DB_PORT=3304
FINANCE_DB_NAME=EDUNOMIC_ERP
DB_USERNAME=admin
DB_PASSWORD=Edunomic@123

#APP PROP
ACCESS_KEY_ID=local
AACCESS_KEY_SECRETE=local

#APPLICATION URI
MASTER_BASE_URL=http://localhost:8085/master
ORGANIZATION_BASE_URL=http://localhost:8090/organization
STUDENT_BASE_URL=http://localhost:8091/student
ADMISSION_BASE_URL=http://localhost:8084/admission
