# CONFIG to IMPORT --spring.config.import=env.properties
server.port=8093
#DATABASE CONFIG
DB_HOST=localhost
DB_PORT=3308
LEAD_DB_NAME=LEAD_MANAGEMENT
DB_USERNAME=admin
DB_PASSWORD=Edunomics@123

#APP
ACCESS_KEY_ID=local
ACCESS_KEY_SECRETE=local

#API URI
ADMISSION_URI=http://localhost:8084
MASTER_URI=http://localhost:8081
STUDENT_BASE_URL=http://localhost:8091
EMPLOYEE_BASE_URL=http://localhost:8092
FINANCE_BASE_URL=http://localhost:8087
NOTIFICATION_URI=http://localhost:8088
ORGFRAMEWOEK_URI=http://localhost:8090