server.port=8085

#DATABASE CONFIG
DB_HOST=localhost
DB_PORT=3302
MASTER_DB_NAME=EDUNOMIC_ERP
DB_USERNAME=master
DB_PASSWORD=Edunomic@123

# APPLICATION CONFIG
MASTER_BASE_URL=http://localhost:8085/master
ACCESS_KEY_ID=local
ACCESS_KEY_SECRETE=local