server.port=8088

#DATABASE CONFIG
DB_HOST=localhost
DB_PORT=3309
NOTIFICATION_DB_NAME=EDUNOMIC_ERP
DB_USERNAME=admin
DB_PASSWORD=Edunomic@123

#APP PROP
ACCESS_KEY_ID=local
ACCESS_KEY_SECRETE=local

#API URL
MASTER_BASE_URL=http://localhost:8085/master
