server.port=8090

#DATABASE CONFIG
DB_HOST=localhost
DB_PORT=3305
ACADEMIC_DB_NAME=EDUNOMIC_ERP
DB_USERNAME=admin
DB_PASSWORD=Edunomic@123

#APPLICATION URI
STUDENT_BASE_URL=http://localhost:8091/student