server.port=8091

#DATABASE CONFIG
DB_HOST=localhost
DB_PORT=3306
STUDENT_DB_NAME=EDUNOMIC_ERP
DB_USERNAME=admin
DB_PASSWORD=Edunomic@123

#APP PROP
ACCESS_KEY_ID=local
ACCESS_KEY_SECRETE=local

#APPLICATION URI
MASTER_BASE_URL=http://localhost:8085/master
ORGANIZATION_BASE_URL=http://localhost:8090/organization
ADMISSION_BASE_URL=http://localhost:8084/admission
EMPLOYEE_BASE_URL=http://localhost:8092/employee
NOTIFICATION_BASE_URL=http://localhost:8088/notification